# Generated by Django 5.2.7 on 2025-10-26 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Meeting data')),
                ('time', models.TimeField(verbose_name='Meeting data')),
                ('is_complete', models.BooleanField()),
                ('rate', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
