# Generated by Django 5.2.7 on 2025-10-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_certificate_owner_experience_owner_meeting_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='meeting',
            field=models.ManyToManyField(to='main_app.meeting'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill',
            field=models.ManyToManyField(to='main_app.skill'),
        ),
    ]
