# Generated by Django 5.2.7 on 2025-10-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_userprofile_meeting_userprofile_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='meeting',
            new_name='meetings',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='skill',
            new_name='skills',
        ),
    ]
