# Generated by Django 5.2.7 on 2025-10-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_meeting_userprofile_meetings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='owner',
        ),
    ]
