# Generated by Django 5.2.7 on 2025-10-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_skill_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='meetings',
            field=models.ManyToManyField(blank=True, to='main_app.meeting'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='main_app.skill'),
        ),
    ]
