# Generated by Django 5.2.7 on 2025-10-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_userprofile_meetings_alter_userprofile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='user',
        ),
    ]
