# Generated by Django 5.2.7 on 2025-10-31 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_meeting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='rate',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(),
        ),
    ]
