# Generated by Django 5.2.7 on 2025-10-31 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_meeting_rate_alter_userprofile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='rate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
