# Generated by Django 5.2.7 on 2025-11-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_meeting_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='meetings',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
