# Generated by Django 5.2.7 on 2025-11-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_meeting_skill_userprofile_userskill_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
