# Generated by Django 5.2.7 on 2025-11-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_delete_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Meeting data')),
                ('starting_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_complete', models.BooleanField()),
            ],
        ),
    ]
