# Generated by Django 5.2.7 on 2025-11-02 15:05

import django.db.models.deletion
import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.meeting', validators=[main_app.models.restrict_amount]),
            preserve_default=False,
        ),
    ]
