# Generated by Django 5.2.7 on 2025-11-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_userprofile_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='meeting',
            new_name='meetings',
        ),
    ]
