# Generated by Django 5.2.7 on 2025-11-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_meeting_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='users',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
