# Generated by Django 5.2.7 on 2025-11-02 21:53

import django.db.models.deletion
import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_remove_meeting_users_alter_meeting_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='meetings',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='main_app.meeting', validators=[main_app.models.restrict_amount]),
            preserve_default=False,
        ),
    ]
