# Generated by Django 5.2.7 on 2025-11-02 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_userprofile_meetings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='meetings',
        ),
    ]
