# Generated by Django 5.2.7 on 2025-11-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='users',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meetings',
            field=models.ManyToManyField(blank=True, to='main_app.meeting'),
        ),
    ]
