# Generated by Django 5.2.7 on 2025-11-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_remove_meeting_users_userprofile_meetings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(unique=True),
        ),
    ]
